# **Ufuncs nedir?**

ufuncs, "Evrensel Fonksiyonlar" anlamına gelir ve nesne üzerinde işlem yapan NumPy fonksiyonlarıdır ndarray.

Ufuncs neden kullanılır?
NumPy'de vektörleştirmeyi uygulamak için ufuncs kullanılır ve bu, elemanlar üzerinde yineleme yapmaktan çok daha hızlıdır.

Ayrıca, hesaplama için çok faydalı olan yayın yapma ve azaltma, biriktirme gibi ek yöntemler de sunarlar.

ufuncs ayrıca şu gibi ek argümanlar da alabilir:

whereİşlemlerin nerede gerçekleşeceğini tanımlayan mantıksal dizi veya koşul.

dtypeÖğelerin dönüş türünü tanımlamak.

outDönüş değerinin kopyalanacağı çıktı dizisi.

Vektörleştirme nedir?
Yinelemeli ifadeleri vektör tabanlı bir işleme dönüştürme işlemine vektörleştirme denir.

Modern işlemciler bu tür işlemler için optimize edildiğinden daha hızlıdır.

İki Listenin Elemanlarını Topla
Liste 1: [1, 2, 3, 4]

Liste 2: [4, 5, 6, 7]

Bunu yapmanın bir yolu, her iki listeyi de yineleyip her bir elemanı toplamaktır.

In [1]:
#ufunc kullanmadan, Python'ın yerleşik yöntemini kullanabiliriz zip():

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [2]:
#add(x, y) NumPy'nin bunun için aynı sonucu verecek bir ufunc'u var .
#ufunc ile şu fonksiyonu kullanabiliriz add():

import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [3]:
#Toplama işlemi için kendi ufunc'unuzu oluşturun:

import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [4]:
#Bir fonksiyonun ufunc olup olmadığını kontrol edin:

import numpy as np

print(type(np.add))

<class 'numpy.ufunc'>


In [ ]:
#Bir fonksiyonun ufunc olup olmadığını kontrol etmek için if ifadesi kullanın:
import numpy as np

if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

# **Basit Aritmetik**

NumPy dizileri arasında doğrudan aritmetik operatörler kullanabilirsiniz , ancak bu bölümde, liste, demet vb. gibi dizi benzeri nesneleri alıp koşullu olarak+ - * / aritmetik işlemler gerçekleştirebilen fonksiyonların bulunduğu bir uzantıdan bahsediliyor .

Şartlı Aritmetik: Aritmetik işlemin gerçekleşmesi gereken koşulları tanımlayabileceğimiz anlamına gelir.

Tartışılan aritmetik fonksiyonların tamamı, wherekoşulu belirtebileceğimiz bir parametre alır.

Ek
Bu add()fonksiyon iki dizinin içeriğini toplar ve sonucu yeni bir dizide döndürür.

In [5]:
#arr1'deki değerleri arr2'deki değerlere ekleyin:

import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [6]:
#arr1'deki değerlerden arr2'deki değerleri çıkarın:

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [7]:
#arr1'deki değerleri arr2'deki değerlerle çarpın:

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [8]:
#arr1'deki değerleri arr2'deki değerlere bölün:

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [9]:
#arr1'deki değerleri arr2'deki değerlerin kuvvetine yükseltin:

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [ ]:
#Kalanları iade edin:

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

In [ ]:
#Kalanları iade edin:

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

In [ ]:
#Dizinin mutlak değerlerini döndürün:

import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

In [10]:
#Aşağıdaki dizinin elemanlarını kırpın:

import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [11]:
#Aynı örnek, şu şekilde fix():

import numpy as np

arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [12]:
#3.1666 sayısını 2 ondalık basamağa yuvarlayın:

import numpy as np

arr = np.around(3.1666, 2)

print(arr)

3.17


In [13]:
#Aşağıdaki dizinin elemanlarını yuvarlayın:

import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [14]:
#ceil() fonksiyonu ondalık sayıları en yakın büyük tam sayıya yuvarlar.

#Örneğin, 3.166'nın tavan değeri 4'tür.
#Aşağıdaki dizinin elemanlarını sıfırlayın:

import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [15]:
#arr1'deki değerleri arr2'deki değerlere ekleyin:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [16]:
#arr1'deki değerleri ve arr2'deki değerleri toplayın:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [17]:
#Aşağıdaki dizideki sayıların 1. eksen üzerindeki toplamını gerçekleştirin:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


Kümülatif Toplam

Kümülatif toplam, dizideki elemanların kısmen toplanması anlamına gelir.

Örneğin, [1, 2, 3, 4]'ün kısmi toplamı [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10] olur.

Fonksiyonu kullanarak kısmi toplama işlemini gerçekleştirin cumsum().

In [18]:
#Aşağıdaki dizide kümülatif toplama işlemini gerçekleştirin:

import numpy as np

arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


In [19]:
#Bu dizinin elemanlarının çarpımını bulun:

import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [20]:
#İki dizinin elemanlarının çarpımını bulun:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


In [21]:
#Aşağıdaki dizideki sayıların 1. eksen üzerindeki toplamını gerçekleştirin:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [22]:
#Aşağıdaki dizinin tüm elemanlarının kümülatif çarpımını alın:

import numpy as np

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


**#Farklılıklar**

Ayrık fark, ardışık iki elemanın birbirinden çıkarılması anlamına gelir.

Örneğin, [1, 2, 3, 4] için, ayrık fark [2-1, 3-2, 4-3] = [1, 1, 1] olur.

Ayrık farkı bulmak için fonksiyonu kullanın diff().

In [23]:
#Aşağıdaki dizinin ayrık farkını hesaplayın:

import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [24]:
#Aşağıdaki dizinin iki kez ayrık farkını hesaplayın:

import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

[  5 -30]


In [25]:
#En Küçük Ortak Katı (EKOK) Bulma

#Aşağıdaki iki sayının en küçük ortak katını bulun:

import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [26]:
#Aşağıdaki dizinin değerlerinin en küçük ortak katını (EKOK) bulun:

import numpy as np

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [27]:
#1'den 10'a kadar olan tüm tamsayıları içeren bir dizinin tüm değerlerinin en küçük ortak katını (EKOK) bulun:

import numpy as np

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


In [28]:
#En Büyük Ortak Böleni (EBOB) Bulma
#Aşağıdaki iki sayının en büyük ortak bölenini bulun:

import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [29]:
#Aşağıdaki dizideki tüm sayıların en büyük ortak bölenini bulun:

import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


In [30]:
#Aşağıdaki tekrarlanan elemanlar içeren diziyi kümeye dönüştürün:

import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [31]:
#Aşağıdaki iki küme dizisinin birleşimini bulun:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [32]:
#Aşağıdaki iki küme dizisinin kesişimini bulun:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


Not: Bu intersect1d()yöntem isteğe bağlı bir argüman alır assume_unique; bu argüman True olarak ayarlanırsa hesaplamayı hızlandırabilir. Kümelerle çalışırken her zaman True olarak ayarlanmalıdır.

In [33]:
#Set1 ile Set2 arasındaki farkı bulun:

import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


In [34]:
#Set1 ve Set2'nin simetrik farkını bulun:

import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
